version: "3.8"
services:
  skycards-bot:
    image: python:3.12-slim
    container_name: skycards-bot
    working_dir: /app
    command: >
      sh -c "python -m pip install --no-cache-dir -r requirements.txt &&
             python -u bot.py"
    env_file:
      - ./.env
    volumes:
      - ./bot.py:/app/bot.py:ro
      - ./rare_hunter.py:/app/rare_hunter.py:ro
      - ./aliases.json:/app/aliases.json:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./aircraft_data:/app/aircraft_data:ro
      - ./watchlist.json:/app/watchlist.json
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport os, json, time\nhealth_file = '/tmp/bot_health.json'\ntry:\n  if os.path.exists(health_file):\n    with open(health_file) as f: data = json.load(f)\n    if time.time() - data.get('last_update', 0) < 300: exit(0)\nexcept: pass\nprint('unhealthy')\nexit(1)\nPY"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s